server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nacos?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.18.128
    port: 5672
    username: guest
    password: guest
    virtual-host: /
logging:
  level:
    com.zhuang: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zhuang.hotel.pojo

